import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>All things serverless</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>

      <main className={styles.main}>
        <div className="logo">
          <img width={100} height={100} src="/favicon.svg" alt="logo" />
        </div>
        <h1 className={styles.title}>
          Welcome to <a>Serverless world!</a>
        </h1>

        <p className={styles.description}>
          Everything around serverless development
        </p>

        <div className={styles.grid}>
          <h1>We are launching soon...</h1>
        </div>
      </main>
    </div>
  );
}
